services:
  svc-backend:
    container_name: svc-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - deep-origin

  svc-frontend:
    container_name: svc-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "4000:4000"
    env_file:
      - ./frontend/src/.env
    volumes:
      - ./frontend:/app
    depends_on:
      - svc-backend
    networks:
      - deep-origin

  svc-postgres:
    image: postgres:16-alpine
    container_name: svc-postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    networks:
      - deep-origin
    volumes:
      - postgres-data-deep-origin:/var/lib/postgresql/data

  svc-postgres-test:
    image: postgres:16-alpine
    container_name: svc-postgres-test
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - "5433:5432"
    networks:
      - deep-origin
    volumes:
      - postgres-data-deep-origin-test:/var/lib/postgresql/data

networks:
  deep-origin:

volumes:
  postgres-data-deep-origin:
  postgres-data-deep-origin-test:
