###
POST http://localhost:3000/api/v1/urls/shorten/create
Content-Type: application/json

{
  "url": "https://www.outlook.com"
}

###
POST http://localhost:3000/api/v1/users/register
Content-Type: application/json

{
  "name": "admin",
  "email": "admin@gmail.com",
  "password": "password"
}

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "password"
}