import React, { useState } from "react";
import DataTable, { TableColumn } from "react-data-table-component";
import { CONSTANTS } from "../../config/constants";
import { useAuth } from "../../contexts/AuthContext";
import { FaRegCopy, FaTrash, FaEdit } from 'react-icons/fa';
import { useHttp } from "../../hooks/useHttp";
import EditModal from "../EditModal/EditModal";

export interface Urls {
  id: number;
  original: string;
  shortened: string;
  hits: number;
}

const UrlsDataTable: React.FC<{ urls: Urls[] }> = ({ urls }) => {
  const { userName } = useAuth();
  const [showToast, setShowToast] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [urlId, setUrlId] = useState(0);

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setShowToast(true);
    setTimeout(() => setShowToast(false), 1000);
  };

  const { remove } = useHttp();

  const handleDelete = async (url: Urls) => {
    try {
      await remove(`${CONSTANTS.url.deleteUrl}/${url.id}`);
      window.location.reload();
    } catch (error) {
      alert("Failed to delete URL");
    }
  };

  const handleEdit = (url: Urls) => {
    setUrlId(url.id);
    setShowModal(true);
  };

  const columns: TableColumn<Urls>[] = [
    {
      name: "Original",
      selector: (row) => row.original,
      sortable: true,
      width: "25rem",
    },
    {
      name: "Shortened",
      cell: (row) => {
        const fullUrl = `${CONSTANTS.url.host}/${row.shortened}`;
        return (
          <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
            <span onClick={() => copyToClipboard(fullUrl)}
            >{fullUrl}</span>
            <FaRegCopy
              onClick={() => copyToClipboard(fullUrl)}
              style={{ cursor: "pointer", color: "#2e4053" }}
              title="Copy to clipboard"
            />
          </div>
        );
      },
      width: "25rem",
      sortable: true,
    },
    {
      name: "Hits",
      selector: (row) => row.hits,
      sortable: true,
    },
    {
      name: "Actions",
      cell: (row) => (
        <div style={{ display: "flex", gap: "10px" }}>
          <FaTrash
            onClick={() => handleDelete(row)}
            style={{ cursor: "pointer", color: "red", fontSize: "1rem" }}
            title="Delete"
          />
          <FaEdit
            onClick={() => handleEdit(row)}
            style={{ cursor: "pointer", color: "#2e4053", fontSize: "1rem" }}
            title="Edit"
          />
        </div>
      ),
    },
  ];

  const customStyles = {
    table: {
      style: {
        boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
        backgroundColor: "#f9f9f9",
        borderRadius: "8px",
      },
    },
    headRow: {
      style: {
        backgroundColor: "#2e4053",
        color: "white",
        fontWeight: "bold",
        fontSize: "16px",
      },
    },
    rows: {
      style: {
        backgroundColor: "#ffffff",
        "&:nth-of-type(odd)": {
          backgroundColor: "#f2f2f2",
        },
      },
    },
    pagination: {
      style: {
        boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
      },
    },
  };

  return (
    <div>

      <EditModal
        show={showModal}
        onHide={() => setShowModal(false)}
        urlId={urlId}
      >
        {"Test"}
      </EditModal>

      {showToast && (
        <div
          className="position-fixed  bottom-0 end-0 m-3 toast show"
          role="alert"
          style={{
            zIndex: 9999,
          }}
        >
          <div className="toast-body bg-success text-white p-3 rounded">
            ✅ Copied
          </div>
        </div>
      )}

      <DataTable
        title={
          <h4 style={{ color: "#000", fontWeight: "bold" }}>
            🚀 Shortened generated by {userName?.split(" ")[0] ?? "User"}
          </h4>
        }
        columns={columns}
        data={urls}
        pagination
        customStyles={customStyles}
        paginationPerPage={5}
        paginationRowsPerPageOptions={[5, 10, 15, 20, 25, 30]}
      />
    </div>
  );
};

export default UrlsDataTable;
